//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIssue.DesktopApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyIssue.DesktopApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;applicationPass&gt;{0}&lt;/applicationPass&gt;
        ///  &lt;companyName&gt;{1}&lt;/companyName&gt;
        ///  &lt;serverAddress&gt;{2}&lt;/serverAddress&gt;
        ///  &lt;port&gt;{3}&lt;/port&gt;
        ///  &lt;login&gt;{4}&lt;/login&gt;
        ///  &lt;pass&gt;{5}&lt;/pass&gt;
        ///  &lt;emailAddress&gt;{6}&lt;/emailAddress&gt;
        ///  &lt;recipientAddress&gt;{7}&lt;/recipientAddress&gt;
        ///  &lt;isSmtp&gt;{8}&lt;/isSmtp&gt;
        ///  &lt;sslTsl&gt;{9}&lt;/sslTsl&gt;
        ///  &lt;image&gt;{10}&lt;/image&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string configuration_xml {
            get {
                return ResourceManager.GetString("configuration.xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;applicationPass&gt;{0}&lt;/applicationPass&gt;
        ///  &lt;companyName&gt;{1}&lt;/companyName&gt;
        ///  &lt;serverAddress&gt;{2}&lt;/serverAddress&gt;
        ///  &lt;port&gt;{3}&lt;/port&gt;
        ///  &lt;login&gt;{4}&lt;/login&gt;
        ///  &lt;pass&gt;{5}&lt;/pass&gt;
        ///  &lt;isSmtp&gt;{6}&lt;/isSmtp&gt;
        ///  &lt;image&gt;{7}&lt;/image&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string configurationServer_xml {
            get {
                return ResourceManager.GetString("configurationServer.xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;userData&gt;
        ///  &lt;name&gt;{0}&lt;/name&gt;
        ///  &lt;surname&gt;{1}&lt;/surname&gt;
        ///  &lt;email&gt;{2}&lt;/email&gt;
        ///  &lt;phone&gt;{3}&lt;/phone&gt;
        ///&lt;/userData&gt;.
        /// </summary>
        internal static string userData_xml {
            get {
                return ResourceManager.GetString("userData.xml", resourceCulture);
            }
        }
    }
}
